---
# - name: Add a global environment variable.
#   lineinfile: "dest=/etc/environment regexp=^DATA_SOURCE_NAME= \
#   line=DATA_SOURCE_NAME={{ mysqld_exporter_data_source_name_env }}"
#   become: yes

- name: ensure Prometheus exporters directory exist
  file:
    path: "{{ mysqld_exporter_install_dir }}"
    state: directory

- name: unarchive MySQL Exporter
  unarchive:
    remote_src: yes
    dest: "{{ mysqld_exporter_install_dir }}"
    src: "{{ mysqld_exporter_url }}"

- name: create symlink to the current release
  file:
    src: "{{ mysqld_exporter_binary }}"
    path: "{{ mysqld_exporter_symlink }}"
    state: link
  notify: restart mysqld exporter

- name: create systemd script
  template:
    src: mysqld_exporter.service.j2
    dest: /etc/systemd/system/mysqld-exporter.service
  notify: restart mysqld exporter

- meta: flush_handlers

- name: make sure MySQL Exporter is started
  service:
    name: mysqld-exporter
    state: started
    enabled: yes